spring:
  application:
    name: fabrica-software
  datasource:
    url: jdbc:postgresql://localhost:5432/fabrica-software
    username: postgres
    password: 200518
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    com.etuniesp.fabrica_software: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configurações de Certificados
app:
  certificados:
    diretorio: ./certificados
    url-base: http://localhost:8080/api/certificados-participacao

